# Generated by Django 3.0.8 on 2020-07-20 17:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('sobrenome', models.CharField(max_length=100, verbose_name='Sobrenome')),
                ('password', models.CharField(max_length=128, verbose_name='Senha')),
                ('bairro', models.CharField(blank=True, max_length=50, verbose_name='Bairro')),
                ('cep', models.CharField(blank=True, max_length=8, verbose_name='CEP')),
                ('endereco', models.CharField(blank=True, max_length=200, verbose_name='Endereço')),
                ('complemento', models.CharField(blank=True, max_length=50, verbose_name='Complemento')),
                ('celular', models.CharField(blank=True, max_length=11, verbose_name='Celular')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(auto_now_add=True, verbose_name='Data do Pedido')),
                ('delivery_date', models.DateField(verbose_name='Data de Entrega')),
                ('status', models.CharField(choices=[('Efetuado', 'Efetuado'), ('Entregue', 'Entregue')], max_length=50)),
                ('transaction_id', models.CharField(max_length=200, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, default=1, null=True)),
                ('categoria', models.CharField(choices=[('Premium - 17cm', 'Premium - 17cm'), ('Premium - 20cm', 'Premium - 20cm'), ('Caseiro', 'Caseiro')], max_length=50)),
                ('massa', models.CharField(max_length=50, verbose_name='Massa')),
                ('recheio', models.CharField(blank=True, max_length=50, verbose_name='Recheio')),
                ('cobertura', models.CharField(blank=True, max_length=50, verbose_name='Cobertura')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Order')),
            ],
        ),
    ]
