# Generated by Django 3.0.8 on 2020-07-29 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='numero',
            field=models.IntegerField(blank=True, null=True),
            preserve_default=False,
        ),
    ]
