# Generated by Django 3.0.8 on 2020-07-30 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_numero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='quantity',
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(default='Entrega', max_length=200, verbose_name='Meio de Entrega'),
        ),
        migrations.AddField(
            model_name='order',
            name='orderPrice',
            field=models.FloatField(blank=True, null=True, verbose_name='Preço'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='itemPrice',
            field=models.FloatField(default=0, verbose_name='Preço do Item'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='categoria',
            field=models.CharField(choices=[('Linha Premium - 15 cm', 'Linha Premium - 15 cm'), ('Linha Premium - 17 cm', 'Linha Premium - 17 cm'), ('Linha Premium - 20 cm', 'Linha Premium - 20 cm'), ('Linha Caseira - 24 cm', 'Linha Caseira - 24 cm')], max_length=50),
        ),
    ]
