# Generated by Django 3.0.8 on 2020-08-06 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200805_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_id',
            field=models.CharField(blank=True, max_length=36, null=True, verbose_name='PaymentId'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Aguardando confirmação de Pagamento', 'Aguardando confirmação de Pagamento'), ('Efetuado - Confirmado', 'Efetuado - Confirmado'), ('Entregue - Finalizado', 'Entregue - Finalizado')], max_length=50),
        ),
    ]
